### ISSUE TITLE
Development 2.0 version discussion

### ISSUE THREAD

**Issue by gephaest** [fpdo/fluentpdo#128]
Hi. I want start discussion about starting development of new version (probably in new 2.0 branch) that contains new PHP modern features and over nice things.
In my opinion, support old PHP version is good but industry evolving very fast and it requires cutting-edge tools with modern approaches.

Please feel free and write your things here.

**Comment by jkufner** [comment]
I already started many months ago :)

Feel free to look at **[Flupdo](https://github.com/jkufner/flupdo)** - it is not a fork, it is completely new code. It is inspired partially by DiBi Fluent (a project related to Nette) and partially by FluentPDO. My motivation was in all libraries being too smart, which makes code harder to read and bugs harder to hunt.

Flupdo is supposed to support 100% syntax of MySQL, Sqlite and Sphinx, however, I probably missed few features. Flupdo does not parse SQL, only glues provided fragments together, so many bugs we can see in Fluentpdo are avoided by definition. The Flupdo code to build a query is slightly longer than with Fluentpdo - it is intentional to provide better readability.

**Comment by mindplay-dk** [comment]
A lot of modernization work was done my @okonomi on [this branch](https://github.com/okonomi/fluentpdo/tree/modernize) a while back, including namespacing and PSR code standards.

@jkufner love the fact that your project formats the generated SQL! - really helpful for diagnostics.

**Comment by jkufner** [comment]
@mindplay-dk Thank you!
